# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://WilsonReese-appdev.github.io/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Reese Wilson
  url:               https://twitter.com/wilsonreese
  email:             reese@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-slate
